function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -1000; // objBuzzBuzz
	global.__objectDepths[1] = -1000; // objFly
	global.__objectDepths[2] = -1000; // objDoubleShotFire
	global.__objectDepths[3] = -1000; // objFireJunker
	global.__objectDepths[4] = -1000; // objBuzzyBastardFire
	global.__objectDepths[5] = -1000; // objDoubleShot
	global.__objectDepths[6] = -180; // objDevil
	global.__objectDepths[7] = -1000; // objFireJunkerCorpse
	global.__objectDepths[8] = -1000; // objBanditTruck
	global.__objectDepths[9] = -1000; // objIceBoneBoy
	global.__objectDepths[10] = 0; // objIceLockerEnemyLenBullet
	global.__objectDepths[11] = -1000; // objSpeep
	global.__objectDepths[12] = 0; // objIceLockerEnemyBullet
	global.__objectDepths[13] = -1000; // objIceLockedEnemy
	global.__objectDepths[14] = -1000; // objSuperMedi
	global.__objectDepths[15] = -1000; // objMediCar
	global.__objectDepths[16] = -1000; // objCandleMan
	global.__objectDepths[17] = -1000; // objLockedEnemy
	global.__objectDepths[18] = -1000; // objJunker
	global.__objectDepths[19] = -180; // objSuperTurretCar
	global.__objectDepths[20] = -1000; // objThreateningBuzzy
	global.__objectDepths[21] = -1000; // objJunkerCorpse
	global.__objectDepths[22] = -180; // objTurretCar
	global.__objectDepths[23] = -1000; // objLockerFire
	global.__objectDepths[24] = -180; // objIceTurretCar
	global.__objectDepths[25] = -10; // objWeakSpawn
	global.__objectDepths[26] = 0; // objHomeBoy
	global.__objectDepths[27] = -180; // objTurretCarFire
	global.__objectDepths[28] = -1000; // objRay
	global.__objectDepths[29] = -450; // objWispBullet
	global.__objectDepths[30] = 0; // objAnnoyance
	global.__objectDepths[31] = 0; // objBlueShifter
	global.__objectDepths[32] = -1000; // objShielder
	global.__objectDepths[33] = 0; // objHellShifter
	global.__objectDepths[34] = -1000; // objRifleman
	global.__objectDepths[35] = 0; // objIceCube
	global.__objectDepths[36] = 0; // objRedShifter
	global.__objectDepths[37] = 0; // objMonk
	global.__objectDepths[38] = -1000; // objUnstableJunker
	global.__objectDepths[39] = -180; // objWisp
	global.__objectDepths[40] = -180; // objWheeler
	global.__objectDepths[41] = 0; // objShifterSmoke
	global.__objectDepths[42] = -1000; // objSmoker
	global.__objectDepths[43] = 0; // objCrystalisk
	global.__objectDepths[44] = -450; // objWasteMine
	global.__objectDepths[45] = 0; // objMediumSpawn
	global.__objectDepths[46] = 0; // objStrainerBullet
	global.__objectDepths[47] = -1000; // objWaste
	global.__objectDepths[48] = -450; // objSnowflakeBullet
	global.__objectDepths[49] = 0; // objLargeSpawn
	global.__objectDepths[50] = 0; // objHellSmokerBullet
	global.__objectDepths[51] = 0; // objIceMage
	global.__objectDepths[52] = -1000; // objHellSmoker
	global.__objectDepths[53] = 0; // objEnemySnowflake
	global.__objectDepths[54] = 0; // objIceMageBullet
	global.__objectDepths[55] = -1000; // objTriple
	global.__objectDepths[56] = -1000; // objStrainer
	global.__objectDepths[57] = 0; // objShifter
	global.__objectDepths[58] = 0; // objTorturedSoul
	global.__objectDepths[59] = 0; // objQuadShot
	global.__objectDepths[60] = -1000; // objSnowBlower
	global.__objectDepths[61] = 0; // objTorturedSoulBullet
	global.__objectDepths[62] = -160; // objWastelandWagon
	global.__objectDepths[63] = -900; // objWastelandDuneMonster
	global.__objectDepths[64] = 0; // objSquid
	global.__objectDepths[65] = 0; // objTubbsy
	global.__objectDepths[66] = 0; // objChainHead
	global.__objectDepths[67] = -1000; // objBoarHerder
	global.__objectDepths[68] = 0; // objSquidFlak
	global.__objectDepths[69] = -1000; // objBoar
	global.__objectDepths[70] = -1000; // objWastelandBully
	global.__objectDepths[71] = 0; // objNeighborhoodGangKid1
	global.__objectDepths[72] = 0; // objNeighborhoodGangKid2
	global.__objectDepths[73] = 0; // objNeighborhoodGang
	global.__objectDepths[74] = 0; // objNeighborhoodGangKid3
	global.__objectDepths[75] = 0; // objFlyingFishWater
	global.__objectDepths[76] = 0; // objTornado
	global.__objectDepths[77] = 0; // objLightningBullet
	global.__objectDepths[78] = 0; // objEyeOfTheStormRain
	global.__objectDepths[79] = -100; // objCloudCreature
	global.__objectDepths[80] = -1000; // objTheMutantLaser
	global.__objectDepths[81] = 0; // objEnemyBubble
	global.__objectDepths[82] = -200; // objSmartBomb
	global.__objectDepths[83] = 0; // objWavyFishBullet
	global.__objectDepths[84] = 0; // objLightningBulletCreature
	global.__objectDepths[85] = 0; // objTheMutantTankShot
	global.__objectDepths[86] = -1000; // objFlyingFish
	global.__objectDepths[87] = -1000; // objTheMutantTank
	global.__objectDepths[88] = -1000; // objEyeOfTheStorm
	global.__objectDepths[89] = 0; // objMutantGrenade
	global.__objectDepths[90] = 0; // objHunterPistolBullet
	global.__objectDepths[91] = 0; // objHorrorFlakShot
	global.__objectDepths[92] = 0; // objTheMutant
	global.__objectDepths[93] = -100; // objSmartBombExplosion
	global.__objectDepths[94] = -1000; // objTheHunterWolves
	global.__objectDepths[95] = 0; // objCrossbowBullet
	global.__objectDepths[96] = 0; // objHorrorAlienShot
	global.__objectDepths[97] = 0; // objShotgunBullet
	global.__objectDepths[98] = 0; // objDeadWoodLaser
	global.__objectDepths[99] = 0; // objCrow
	global.__objectDepths[100] = 0; // objHorrorGhost
	global.__objectDepths[101] = 0; // objChainsaw
	global.__objectDepths[102] = -1000; // objDeadWood
	global.__objectDepths[103] = -1000; // objTheHunter
	global.__objectDepths[104] = -1000; // objHorrorApparition
	global.__objectDepths[105] = -727379968; // objDarkness
	global.__objectDepths[106] = 0; // objFlakFire
	global.__objectDepths[107] = 0; // objFireMageFireball
	global.__objectDepths[108] = 0; // objFireIndicator
	global.__objectDepths[109] = 0; // objGrappleHookBullet
	global.__objectDepths[110] = -10; // objMinibossSpawn
	global.__objectDepths[111] = 0; // objDeathKid1Bullet
	global.__objectDepths[112] = 0; // objFireBurst
	global.__objectDepths[113] = 0; // objEnemyBouncyBullet
	global.__objectDepths[114] = -1100; // objMuttBossTurret
	global.__objectDepths[115] = 0; // objDeathGangKid1
	global.__objectDepths[116] = 0; // objGrapplingHookShot
	global.__objectDepths[117] = -1000; // objBanditCaravan
	global.__objectDepths[118] = 0; // objDeathGangKid3
	global.__objectDepths[119] = 0; // objDeathGangKid2
	global.__objectDepths[120] = 0; // objDeathGang
	global.__objectDepths[121] = -1000; // objFireMage
	global.__objectDepths[122] = 0; // objBurp
	global.__objectDepths[123] = -1400; // objMuttBossWheel
	global.__objectDepths[124] = -15000; // objMuttBossOpen
	global.__objectDepths[125] = 0; // objFlakMiniShot
	global.__objectDepths[126] = 0; // objGrape
	global.__objectDepths[127] = 0; // objAcidBullet
	global.__objectDepths[128] = -1500; // objGrapeCarrier
	global.__objectDepths[129] = 0; // objKnightLaser
	global.__objectDepths[130] = 0; // objLaserWater
	global.__objectDepths[131] = -1005; // objParasiteWorm
	global.__objectDepths[132] = -1000; // objMiniCaravan
	global.__objectDepths[133] = -1000; // objKingBubbs
	global.__objectDepths[134] = 0; // objUFOMissle
	global.__objectDepths[135] = -1000; // objKnight
	global.__objectDepths[136] = -100000; // objUFO
	global.__objectDepths[137] = 0; // objFlakShot
	global.__objectDepths[138] = 0; // objSpookyScottBuddyShot
	global.__objectDepths[139] = -2000; // objParasiteWormShot
	global.__objectDepths[140] = 0; // objPlagueBulletCircle
	global.__objectDepths[141] = 0; // objGlowingBullet
	global.__objectDepths[142] = 0; // objAlienPixie
	global.__objectDepths[143] = 0; // objPixieBullet
	global.__objectDepths[144] = 0; // objGhostBullet
	global.__objectDepths[145] = 0; // objWavyAcidBullet
	global.__objectDepths[146] = -1000; // objSpookyScottBuddy
	global.__objectDepths[147] = 0; // objThePlagueSpore
	global.__objectDepths[148] = 0; // objSpookyScottSquirmer
	global.__objectDepths[149] = 0; // objInvisibleBullet
	global.__objectDepths[150] = -1000; // objParasiteWormBody
	global.__objectDepths[151] = -1000; // objSpookyScott
	global.__objectDepths[152] = -1000; // objThePlague
	global.__objectDepths[153] = -450; // objThePlagueCircleBullet
	global.__objectDepths[154] = 0; // objPixie
	global.__objectDepths[155] = -100; // objIllusionLaserStart
	global.__objectDepths[156] = -500; // objNaturesBaneEnemyStar
	global.__objectDepths[157] = 0; // objIllusionMiddleWaveBullet
	global.__objectDepths[158] = 0; // objNaturesBaneWall
	global.__objectDepths[159] = -1005; // objIllusionNormalBullet
	global.__objectDepths[160] = -105; // objIllusionLaser
	global.__objectDepths[161] = -110; // objIllusionBullet
	global.__objectDepths[162] = 0; // objNaturesBaneCircleBulletSpecial
	global.__objectDepths[163] = -450; // objNaturesBaneCircleBullet
	global.__objectDepths[164] = -1400; // objIllusionHand
	global.__objectDepths[165] = -450; // objNaturesBaneDebrisShot
	global.__objectDepths[166] = -1000; // objCarriageOfIllusion
	global.__objectDepths[167] = 0; // objNaturesBaneBulletCircle
	global.__objectDepths[168] = -1000; // objPixieStorm
	global.__objectDepths[169] = -1000; // objNaturesBane
	global.__objectDepths[170] = 0; // objGorganZipperShot
	global.__objectDepths[171] = 0; // objQueenOfFliesLarvaeFly
	global.__objectDepths[172] = 0; // objGorganSine
	global.__objectDepths[173] = 0; // objGorganWall
	global.__objectDepths[174] = 0; // objQueenOfFliesLarvae
	global.__objectDepths[175] = 0; // objQueenOfFliesBullet
	global.__objectDepths[176] = 0; // objGorganZipper
	global.__objectDepths[177] = -1000; // objQueenOfFliesFastMinibossBodyBullet
	global.__objectDepths[178] = 0; // objPulseShot
	global.__objectDepths[179] = 0; // objWallCreator
	global.__objectDepths[180] = 0; // objTinyFastFly
	global.__objectDepths[181] = 0; // objTinyStrongFly
	global.__objectDepths[182] = -1000; // objGorgan
	global.__objectDepths[183] = -1000; // objQueenOfFlies
	global.__objectDepths[184] = -1000; // objQueenOfFliesFastMiniboss
	global.__objectDepths[185] = -1000; // objQueenOfFliesStrongMiniboss
	global.__objectDepths[186] = 0; // objTankRocket
	global.__objectDepths[187] = 0; // objEnemyTimeBullet
	global.__objectDepths[188] = 0; // objRocketBullet
	global.__objectDepths[189] = 0; // objMilitaryWeaponFlak
	global.__objectDepths[190] = 0; // objMilitaryWeaponryBullet
	global.__objectDepths[191] = 0; // objMilitaryWeaponMine
	global.__objectDepths[192] = 0; // objTimeSineBullet
	global.__objectDepths[193] = 0; // objRetractingBullets
	global.__objectDepths[194] = 0; // objTankFlak
	global.__objectDepths[195] = -1000; // objMilitaryWeaponry
	global.__objectDepths[196] = 0; // objMilitaryWeaponTurret
	global.__objectDepths[197] = -1000; // objTankOfFlame
	global.__objectDepths[198] = -1000; // objAnarchistOfTime
	global.__objectDepths[199] = -1000; // objKingBorbs
	global.__objectDepths[200] = 0; // objSpiralFlak
	global.__objectDepths[201] = 0; // objRetractingBigBullet
	global.__objectDepths[202] = 0; // objShriBullet
	global.__objectDepths[203] = 0; // objKingBorbsBubble
	global.__objectDepths[204] = 0; // objFinalBossYellowBullet
	global.__objectDepths[205] = 0; // objTheGlitchBullet
	global.__objectDepths[206] = 0; // objKingBorbsSnakeBullet
	global.__objectDepths[207] = 0; // objKingBorbsClam
	global.__objectDepths[208] = 0; // objFinalBossBulletWave
	global.__objectDepths[209] = 0; // objTheGlitchFadeBullet
	global.__objectDepths[210] = 0; // objFinalBossBlockingBulletExtra
	global.__objectDepths[211] = 0; // objTheGlitchZigBullet
	global.__objectDepths[212] = -1000; // objTheFinalBoss
	global.__objectDepths[213] = -1000; // objTheGlitch
	global.__objectDepths[214] = 0; // objKingBorbsBullet
	global.__objectDepths[215] = -5; // objFinalBossBlockingBullet
	global.__objectDepths[216] = -1000; // objTombOfShri
	global.__objectDepths[217] = 0; // objKingBorbsFish
	global.__objectDepths[218] = 0; // objHellSnake
	global.__objectDepths[219] = -450; // objBanditBullet
	global.__objectDepths[220] = 0; // objSatanBullet
	global.__objectDepths[221] = -1000; // objSatanRock
	global.__objectDepths[222] = 0; // objRisingFire
	global.__objectDepths[223] = 0; // objRadiusWall
	global.__objectDepths[224] = 0; // objTheGodZoomInBullet
	global.__objectDepths[225] = -10; // objBossSpawn
	global.__objectDepths[226] = 0; // objFinalBossSineWave2
	global.__objectDepths[227] = 35; // objSatan
	global.__objectDepths[228] = -1000; // objFinalBossLenBullet
	global.__objectDepths[229] = 0; // objBigFlak
	global.__objectDepths[230] = 0; // objLightBlast
	global.__objectDepths[231] = 0; // objFinalBossSineWave1
	global.__objectDepths[232] = -1500; // objBossText
	global.__objectDepths[233] = 10; // objTheGod
	global.__objectDepths[234] = 0; // objGlobalControl
	global.__objectDepths[235] = 0; // objEnemyMiniFire
	global.__objectDepths[236] = -450; // objEnemyFollowBullet
	global.__objectDepths[237] = 0; // objFreezeEnemy
	global.__objectDepths[238] = 0; // objEnemyRocket
	global.__objectDepths[239] = -450; // objEnemyBulletStatic
	global.__objectDepths[240] = -450; // objEnemyBullet
	global.__objectDepths[241] = 0; // objCutscene
	global.__objectDepths[242] = 0; // objEnemyFireball
	global.__objectDepths[243] = 25; // objBoat
	global.__objectDepths[244] = -1000000000; // objGameControl
	global.__objectDepths[245] = 0; // objRareBird
	global.__objectDepths[246] = -1000; // objMimic
	global.__objectDepths[247] = 20; // objBackgroundControl
	global.__objectDepths[248] = -100000000; // objEntpMedallionControl
	global.__objectDepths[249] = 0; // objEnemyCannonball
	global.__objectDepths[250] = 0; // objBulletParent
	global.__objectDepths[251] = 0; // objBackgroundParent
	global.__objectDepths[252] = 0; // objShopParent
	global.__objectDepths[253] = 0; // objWindowControl
	global.__objectDepths[254] = 0; // objParentMedium
	global.__objectDepths[255] = 0; // objAshFromExpl
	global.__objectDepths[256] = 0; // objGibParent
	global.__objectDepths[257] = -100; // objParentWeak
	global.__objectDepths[258] = 19; // objShadowControl
	global.__objectDepths[259] = -100; // objEnemyParent
	global.__objectDepths[260] = 0; // objBuyParent
	global.__objectDepths[261] = -1000; // objEnemyBulletParent
	global.__objectDepths[262] = 0; // objPauseParent
	global.__objectDepths[263] = 0; // objMenuControl
	global.__objectDepths[264] = -10000; // objPauseControl
	global.__objectDepths[265] = -100; // objBossParent
	global.__objectDepths[266] = 0; // objBlood
	global.__objectDepths[267] = 50; // objBackgroundBird
	global.__objectDepths[268] = 0; // objBloodExplosion
	global.__objectDepths[269] = -1316134912; // objFadeAway
	global.__objectDepths[270] = 0; // objRoadDecal
	global.__objectDepths[271] = 0; // objExplosion
	global.__objectDepths[272] = 95; // objLightning
	global.__objectDepths[273] = 95; // objFartherClouds
	global.__objectDepths[274] = 80; // objClouds
	global.__objectDepths[275] = 0; // objBridge
	global.__objectDepths[276] = 100; // objSkyline
	global.__objectDepths[277] = -1500; // objRocks
	global.__objectDepths[278] = -1000000000; // objFade
	global.__objectDepths[279] = 90; // objFartherBackground
	global.__objectDepths[280] = 40; // objBackground
	global.__objectDepths[281] = 50; // objFarBackground
	global.__objectDepths[282] = 0; // objStormGrey
	global.__objectDepths[283] = -100; // objRainDrop
	global.__objectDepths[284] = 0; // objIndicatorParticle
	global.__objectDepths[285] = -500; // objSmoke
	global.__objectDepths[286] = -1500; // objGiblet
	global.__objectDepths[287] = -1000000; // objFlash
	global.__objectDepths[288] = 23; // objFireDebris
	global.__objectDepths[289] = 0; // objTeleportLine
	global.__objectDepths[290] = 0; // objTeleport
	global.__objectDepths[291] = -100000; // objGameBeginFade
	global.__objectDepths[292] = 0; // objJunkPile
	global.__objectDepths[293] = 27; // objForestFartherBackground
	global.__objectDepths[294] = 18; // objJunkWall
	global.__objectDepths[295] = 25; // objForestBackground
	global.__objectDepths[296] = 29; // objForestFarthestBackground
	global.__objectDepths[297] = 20; // objRoad
	global.__objectDepths[298] = 0; // objPlayer2
	global.__objectDepths[299] = 0; // objFriendlyJunker
	global.__objectDepths[300] = -1400; // objThickSmoke
	global.__objectDepths[301] = 0; // objAirstrike
	global.__objectDepths[302] = 0; // objSmokeCanister
	global.__objectDepths[303] = 0; // objShadowManip
	global.__objectDepths[304] = 0; // objRocketGuide
	global.__objectDepths[305] = 0; // objBulletShell
	global.__objectDepths[306] = -10000; // objGunFlash
	global.__objectDepths[307] = -100; // objSweat
	global.__objectDepths[308] = 0; // objHelicopter
	global.__objectDepths[309] = 0; // objSoulStat
	global.__objectDepths[310] = 0; // objPickup
	global.__objectDepths[311] = -300; // objArrow
	global.__objectDepths[312] = -1000; // objFriendlyJunkerCorpse
	global.__objectDepths[313] = -120; // objPlayer
	global.__objectDepths[314] = -300; // objSquareFollower
	global.__objectDepths[315] = -300; // objMomentumBullet
	global.__objectDepths[316] = 0; // objFlappyBullet
	global.__objectDepths[317] = -300; // objPredictorBullet
	global.__objectDepths[318] = 0; // objBoomerang
	global.__objectDepths[319] = -300; // objFireball
	global.__objectDepths[320] = -300; // objCircleBullet
	global.__objectDepths[321] = 0; // objDove
	global.__objectDepths[322] = 0; // objBulletDestroy
	global.__objectDepths[323] = -300; // objInfectionShot
	global.__objectDepths[324] = 0; // objDoveCorpse
	global.__objectDepths[325] = 0; // objGrenade
	global.__objectDepths[326] = -300; // objBurstBullet
	global.__objectDepths[327] = -300; // objBullet
	global.__objectDepths[328] = 0; // objCannonball
	global.__objectDepths[329] = -300; // objCircle
	global.__objectDepths[330] = 0; // objLaser
	global.__objectDepths[331] = 0; // objApple
	global.__objectDepths[332] = -1000; // objBee
	global.__objectDepths[333] = 0; // objBrickBreaker
	global.__objectDepths[334] = 0; // objBestFriend
	global.__objectDepths[335] = 0; // objBulletPortal
	global.__objectDepths[336] = 0; // objPoisonCloud
	global.__objectDepths[337] = -300; // objMeleeSwing
	global.__objectDepths[338] = 0; // objBabyTurret
	global.__objectDepths[339] = 0; // objScreamer
	global.__objectDepths[340] = -300; // objSlingshot
	global.__objectDepths[341] = 0; // objBoneBoyCircle
	global.__objectDepths[342] = 0; // objScreamerWave
	global.__objectDepths[343] = 0; // objBalloon
	global.__objectDepths[344] = 0; // objLilPupper
	global.__objectDepths[345] = 0; // objViolentExplosion
	global.__objectDepths[346] = 0; // objRocket
	global.__objectDepths[347] = 0; // objHeartBullet
	global.__objectDepths[348] = 0; // objFlippy
	global.__objectDepths[349] = -130; // objFriendlyDevil
	global.__objectDepths[350] = 0; // objCigarSmoke
	global.__objectDepths[351] = 0; // objFlippyBullet
	global.__objectDepths[352] = -300; // objHandBullet
	global.__objectDepths[353] = -1000000; // objVenomsKiss
	global.__objectDepths[354] = 0; // objInstantLine
	global.__objectDepths[355] = -300; // objGuardianAngel
	global.__objectDepths[356] = -300; // objMiniFireball
	global.__objectDepths[357] = 0; // objDespairShield
	global.__objectDepths[358] = -10000; // objGunpowderBlood
	global.__objectDepths[359] = -130; // objHeliTurret
	global.__objectDepths[360] = 0; // objHelpingHand
	global.__objectDepths[361] = 0; // objLilPuffer
	global.__objectDepths[362] = 0; // objGum
	global.__objectDepths[363] = 0; // objSlider
	global.__objectDepths[364] = -100000; // objStatArrow
	global.__objectDepths[365] = 0; // objSnowball
	global.__objectDepths[366] = 0; // objStatsButton
	global.__objectDepths[367] = 0; // objSnakeBullet
	global.__objectDepths[368] = 0; // objArtifactsPullDown
	global.__objectDepths[369] = 0; // objSuperBomb
	global.__objectDepths[370] = -10; // objArtifactSelectArrow
	global.__objectDepths[371] = -10; // objArtifactMedal
	global.__objectDepths[372] = -300; // objMiniFire
	global.__objectDepths[373] = 0; // objArtifactBar
	global.__objectDepths[374] = 0; // objPlayerSelectArrow
	global.__objectDepths[375] = -1000; // objSliderGrab
	global.__objectDepths[376] = -130; // objSnowIdol
	global.__objectDepths[377] = -1000; // objSniperSupport
	global.__objectDepths[378] = -1000; // objPickupEater
	global.__objectDepths[379] = 0; // objCharactersPullDown
	global.__objectDepths[380] = -10000; // objBackToMenu
	global.__objectDepths[381] = 0; // objEnemiesTab
	global.__objectDepths[382] = -10000000; // objTitleD
	global.__objectDepths[383] = 0; // objCoopArrow
	global.__objectDepths[384] = -100000000; // objEntpMedallionButton
	global.__objectDepths[385] = -10000000; // objCreatedBy
	global.__objectDepths[386] = 0; // objGoButton
	global.__objectDepths[387] = -100; // objQuitButton
	global.__objectDepths[388] = 0; // objChallengesButton
	global.__objectDepths[389] = 0; // objEntpMedallionArrow
	global.__objectDepths[390] = 0; // objChallengeText
	global.__objectDepths[391] = -10000; // objChangelog
	global.__objectDepths[392] = -100000; // objLevelName
	global.__objectDepths[393] = 0; // objCharacterBar
	global.__objectDepths[394] = -10000; // objEnemyTypeBox
	global.__objectDepths[395] = -1000000; // objPauseItem
	global.__objectDepths[396] = 0; // objItemsTab
	global.__objectDepths[397] = 0; // objPauseMenuRestart
	global.__objectDepths[398] = 0; // objPauseMenuMousePoint
	global.__objectDepths[399] = -10; // objGoCoopButton
	global.__objectDepths[400] = 0; // objPauseMenuQuit
	global.__objectDepths[401] = 0; // objPauseMenuResume
	global.__objectDepths[402] = 0; // objStatsTab
	global.__objectDepths[403] = 15; // objMenuHalfFade
	global.__objectDepths[404] = 0; // objPlayButton
	global.__objectDepths[405] = -1000000; // objPausedText
	global.__objectDepths[406] = 0; // objStatsHud
	global.__objectDepths[407] = 0; // objPauseMenuOptions
	global.__objectDepths[408] = 0; // objCheckBox
	global.__objectDepths[409] = -1000000; // objPauseLetter
	global.__objectDepths[410] = -10000; // objItemTypeBox
	global.__objectDepths[411] = -100; // objGamblingMachine
	global.__objectDepths[412] = 0; // objWeaponTree
	global.__objectDepths[413] = 10; // objPlayerSelect
	global.__objectDepths[414] = -10000; // objRestart
	global.__objectDepths[415] = -100; // objExitButton
	global.__objectDepths[416] = -300; // objHealth
	global.__objectDepths[417] = -1000000; // objStatBox
	global.__objectDepths[418] = -150; // objGamblingLights
	global.__objectDepths[419] = -100; // objBossMaster
	global.__objectDepths[420] = -700; // objGun
	global.__objectDepths[421] = -180; // objGamblingWin
	global.__objectDepths[422] = -200; // objGamblingDispense
	global.__objectDepths[423] = -1000000; // objTitleOtherLetters
	global.__objectDepths[424] = -100000; // objTicketOfAdmission
	global.__objectDepths[425] = -170; // objGamblingRoll
	global.__objectDepths[426] = -100; // objBuyButton
	global.__objectDepths[427] = -500; // objHealthRobot
	global.__objectDepths[428] = -700; // objItem
	global.__objectDepths[429] = -200; // objScroll
	global.__objectDepths[430] = -200; // objUseItem
	global.__objectDepths[431] = 10; // objShop
	global.__objectDepths[432] = 12; // objShopkeeper


	global.__objectNames[0] = "objBuzzBuzz";
	global.__objectNames[1] = "objFly";
	global.__objectNames[2] = "objDoubleShotFire";
	global.__objectNames[3] = "objFireJunker";
	global.__objectNames[4] = "objBuzzyBastardFire";
	global.__objectNames[5] = "objDoubleShot";
	global.__objectNames[6] = "objDevil";
	global.__objectNames[7] = "objFireJunkerCorpse";
	global.__objectNames[8] = "objBanditTruck";
	global.__objectNames[9] = "objIceBoneBoy";
	global.__objectNames[10] = "objIceLockerEnemyLenBullet";
	global.__objectNames[11] = "objSpeep";
	global.__objectNames[12] = "objIceLockerEnemyBullet";
	global.__objectNames[13] = "objIceLockedEnemy";
	global.__objectNames[14] = "objSuperMedi";
	global.__objectNames[15] = "objMediCar";
	global.__objectNames[16] = "objCandleMan";
	global.__objectNames[17] = "objLockedEnemy";
	global.__objectNames[18] = "objJunker";
	global.__objectNames[19] = "objSuperTurretCar";
	global.__objectNames[20] = "objThreateningBuzzy";
	global.__objectNames[21] = "objJunkerCorpse";
	global.__objectNames[22] = "objTurretCar";
	global.__objectNames[23] = "objLockerFire";
	global.__objectNames[24] = "objIceTurretCar";
	global.__objectNames[25] = "objWeakSpawn";
	global.__objectNames[26] = "objHomeBoy";
	global.__objectNames[27] = "objTurretCarFire";
	global.__objectNames[28] = "objRay";
	global.__objectNames[29] = "objWispBullet";
	global.__objectNames[30] = "objAnnoyance";
	global.__objectNames[31] = "objBlueShifter";
	global.__objectNames[32] = "objShielder";
	global.__objectNames[33] = "objHellShifter";
	global.__objectNames[34] = "objRifleman";
	global.__objectNames[35] = "objIceCube";
	global.__objectNames[36] = "objRedShifter";
	global.__objectNames[37] = "objMonk";
	global.__objectNames[38] = "objUnstableJunker";
	global.__objectNames[39] = "objWisp";
	global.__objectNames[40] = "objWheeler";
	global.__objectNames[41] = "objShifterSmoke";
	global.__objectNames[42] = "objSmoker";
	global.__objectNames[43] = "objCrystalisk";
	global.__objectNames[44] = "objWasteMine";
	global.__objectNames[45] = "objMediumSpawn";
	global.__objectNames[46] = "objStrainerBullet";
	global.__objectNames[47] = "objWaste";
	global.__objectNames[48] = "objSnowflakeBullet";
	global.__objectNames[49] = "objLargeSpawn";
	global.__objectNames[50] = "objHellSmokerBullet";
	global.__objectNames[51] = "objIceMage";
	global.__objectNames[52] = "objHellSmoker";
	global.__objectNames[53] = "objEnemySnowflake";
	global.__objectNames[54] = "objIceMageBullet";
	global.__objectNames[55] = "objTriple";
	global.__objectNames[56] = "objStrainer";
	global.__objectNames[57] = "objShifter";
	global.__objectNames[58] = "objTorturedSoul";
	global.__objectNames[59] = "objQuadShot";
	global.__objectNames[60] = "objSnowBlower";
	global.__objectNames[61] = "objTorturedSoulBullet";
	global.__objectNames[62] = "objWastelandWagon";
	global.__objectNames[63] = "objWastelandDuneMonster";
	global.__objectNames[64] = "objSquid";
	global.__objectNames[65] = "objTubbsy";
	global.__objectNames[66] = "objChainHead";
	global.__objectNames[67] = "objBoarHerder";
	global.__objectNames[68] = "objSquidFlak";
	global.__objectNames[69] = "objBoar";
	global.__objectNames[70] = "objWastelandBully";
	global.__objectNames[71] = "objNeighborhoodGangKid1";
	global.__objectNames[72] = "objNeighborhoodGangKid2";
	global.__objectNames[73] = "objNeighborhoodGang";
	global.__objectNames[74] = "objNeighborhoodGangKid3";
	global.__objectNames[75] = "objFlyingFishWater";
	global.__objectNames[76] = "objTornado";
	global.__objectNames[77] = "objLightningBullet";
	global.__objectNames[78] = "objEyeOfTheStormRain";
	global.__objectNames[79] = "objCloudCreature";
	global.__objectNames[80] = "objTheMutantLaser";
	global.__objectNames[81] = "objEnemyBubble";
	global.__objectNames[82] = "objSmartBomb";
	global.__objectNames[83] = "objWavyFishBullet";
	global.__objectNames[84] = "objLightningBulletCreature";
	global.__objectNames[85] = "objTheMutantTankShot";
	global.__objectNames[86] = "objFlyingFish";
	global.__objectNames[87] = "objTheMutantTank";
	global.__objectNames[88] = "objEyeOfTheStorm";
	global.__objectNames[89] = "objMutantGrenade";
	global.__objectNames[90] = "objHunterPistolBullet";
	global.__objectNames[91] = "objHorrorFlakShot";
	global.__objectNames[92] = "objTheMutant";
	global.__objectNames[93] = "objSmartBombExplosion";
	global.__objectNames[94] = "objTheHunterWolves";
	global.__objectNames[95] = "objCrossbowBullet";
	global.__objectNames[96] = "objHorrorAlienShot";
	global.__objectNames[97] = "objShotgunBullet";
	global.__objectNames[98] = "objDeadWoodLaser";
	global.__objectNames[99] = "objCrow";
	global.__objectNames[100] = "objHorrorGhost";
	global.__objectNames[101] = "objChainsaw";
	global.__objectNames[102] = "objDeadWood";
	global.__objectNames[103] = "objTheHunter";
	global.__objectNames[104] = "objHorrorApparition";
	global.__objectNames[105] = "objDarkness";
	global.__objectNames[106] = "objFlakFire";
	global.__objectNames[107] = "objFireMageFireball";
	global.__objectNames[108] = "objFireIndicator";
	global.__objectNames[109] = "objGrappleHookBullet";
	global.__objectNames[110] = "objMinibossSpawn";
	global.__objectNames[111] = "objDeathKid1Bullet";
	global.__objectNames[112] = "objFireBurst";
	global.__objectNames[113] = "objEnemyBouncyBullet";
	global.__objectNames[114] = "objMuttBossTurret";
	global.__objectNames[115] = "objDeathGangKid1";
	global.__objectNames[116] = "objGrapplingHookShot";
	global.__objectNames[117] = "objBanditCaravan";
	global.__objectNames[118] = "objDeathGangKid3";
	global.__objectNames[119] = "objDeathGangKid2";
	global.__objectNames[120] = "objDeathGang";
	global.__objectNames[121] = "objFireMage";
	global.__objectNames[122] = "objBurp";
	global.__objectNames[123] = "objMuttBossWheel";
	global.__objectNames[124] = "objMuttBossOpen";
	global.__objectNames[125] = "objFlakMiniShot";
	global.__objectNames[126] = "objGrape";
	global.__objectNames[127] = "objAcidBullet";
	global.__objectNames[128] = "objGrapeCarrier";
	global.__objectNames[129] = "objKnightLaser";
	global.__objectNames[130] = "objLaserWater";
	global.__objectNames[131] = "objParasiteWorm";
	global.__objectNames[132] = "objMiniCaravan";
	global.__objectNames[133] = "objKingBubbs";
	global.__objectNames[134] = "objUFOMissle";
	global.__objectNames[135] = "objKnight";
	global.__objectNames[136] = "objUFO";
	global.__objectNames[137] = "objFlakShot";
	global.__objectNames[138] = "objSpookyScottBuddyShot";
	global.__objectNames[139] = "objParasiteWormShot";
	global.__objectNames[140] = "objPlagueBulletCircle";
	global.__objectNames[141] = "objGlowingBullet";
	global.__objectNames[142] = "objAlienPixie";
	global.__objectNames[143] = "objPixieBullet";
	global.__objectNames[144] = "objGhostBullet";
	global.__objectNames[145] = "objWavyAcidBullet";
	global.__objectNames[146] = "objSpookyScottBuddy";
	global.__objectNames[147] = "objThePlagueSpore";
	global.__objectNames[148] = "objSpookyScottSquirmer";
	global.__objectNames[149] = "objInvisibleBullet";
	global.__objectNames[150] = "objParasiteWormBody";
	global.__objectNames[151] = "objSpookyScott";
	global.__objectNames[152] = "objThePlague";
	global.__objectNames[153] = "objThePlagueCircleBullet";
	global.__objectNames[154] = "objPixie";
	global.__objectNames[155] = "objIllusionLaserStart";
	global.__objectNames[156] = "objNaturesBaneEnemyStar";
	global.__objectNames[157] = "objIllusionMiddleWaveBullet";
	global.__objectNames[158] = "objNaturesBaneWall";
	global.__objectNames[159] = "objIllusionNormalBullet";
	global.__objectNames[160] = "objIllusionLaser";
	global.__objectNames[161] = "objIllusionBullet";
	global.__objectNames[162] = "objNaturesBaneCircleBulletSpecial";
	global.__objectNames[163] = "objNaturesBaneCircleBullet";
	global.__objectNames[164] = "objIllusionHand";
	global.__objectNames[165] = "objNaturesBaneDebrisShot";
	global.__objectNames[166] = "objCarriageOfIllusion";
	global.__objectNames[167] = "objNaturesBaneBulletCircle";
	global.__objectNames[168] = "objPixieStorm";
	global.__objectNames[169] = "objNaturesBane";
	global.__objectNames[170] = "objGorganZipperShot";
	global.__objectNames[171] = "objQueenOfFliesLarvaeFly";
	global.__objectNames[172] = "objGorganSine";
	global.__objectNames[173] = "objGorganWall";
	global.__objectNames[174] = "objQueenOfFliesLarvae";
	global.__objectNames[175] = "objQueenOfFliesBullet";
	global.__objectNames[176] = "objGorganZipper";
	global.__objectNames[177] = "objQueenOfFliesFastMinibossBodyBullet";
	global.__objectNames[178] = "objPulseShot";
	global.__objectNames[179] = "objWallCreator";
	global.__objectNames[180] = "objTinyFastFly";
	global.__objectNames[181] = "objTinyStrongFly";
	global.__objectNames[182] = "objGorgan";
	global.__objectNames[183] = "objQueenOfFlies";
	global.__objectNames[184] = "objQueenOfFliesFastMiniboss";
	global.__objectNames[185] = "objQueenOfFliesStrongMiniboss";
	global.__objectNames[186] = "objTankRocket";
	global.__objectNames[187] = "objEnemyTimeBullet";
	global.__objectNames[188] = "objRocketBullet";
	global.__objectNames[189] = "objMilitaryWeaponFlak";
	global.__objectNames[190] = "objMilitaryWeaponryBullet";
	global.__objectNames[191] = "objMilitaryWeaponMine";
	global.__objectNames[192] = "objTimeSineBullet";
	global.__objectNames[193] = "objRetractingBullets";
	global.__objectNames[194] = "objTankFlak";
	global.__objectNames[195] = "objMilitaryWeaponry";
	global.__objectNames[196] = "objMilitaryWeaponTurret";
	global.__objectNames[197] = "objTankOfFlame";
	global.__objectNames[198] = "objAnarchistOfTime";
	global.__objectNames[199] = "objKingBorbs";
	global.__objectNames[200] = "objSpiralFlak";
	global.__objectNames[201] = "objRetractingBigBullet";
	global.__objectNames[202] = "objShriBullet";
	global.__objectNames[203] = "objKingBorbsBubble";
	global.__objectNames[204] = "objFinalBossYellowBullet";
	global.__objectNames[205] = "objTheGlitchBullet";
	global.__objectNames[206] = "objKingBorbsSnakeBullet";
	global.__objectNames[207] = "objKingBorbsClam";
	global.__objectNames[208] = "objFinalBossBulletWave";
	global.__objectNames[209] = "objTheGlitchFadeBullet";
	global.__objectNames[210] = "objFinalBossBlockingBulletExtra";
	global.__objectNames[211] = "objTheGlitchZigBullet";
	global.__objectNames[212] = "objTheFinalBoss";
	global.__objectNames[213] = "objTheGlitch";
	global.__objectNames[214] = "objKingBorbsBullet";
	global.__objectNames[215] = "objFinalBossBlockingBullet";
	global.__objectNames[216] = "objTombOfShri";
	global.__objectNames[217] = "objKingBorbsFish";
	global.__objectNames[218] = "objHellSnake";
	global.__objectNames[219] = "objBanditBullet";
	global.__objectNames[220] = "objSatanBullet";
	global.__objectNames[221] = "objSatanRock";
	global.__objectNames[222] = "objRisingFire";
	global.__objectNames[223] = "objRadiusWall";
	global.__objectNames[224] = "objTheGodZoomInBullet";
	global.__objectNames[225] = "objBossSpawn";
	global.__objectNames[226] = "objFinalBossSineWave2";
	global.__objectNames[227] = "objSatan";
	global.__objectNames[228] = "objFinalBossLenBullet";
	global.__objectNames[229] = "objBigFlak";
	global.__objectNames[230] = "objLightBlast";
	global.__objectNames[231] = "objFinalBossSineWave1";
	global.__objectNames[232] = "objBossText";
	global.__objectNames[233] = "objTheGod";
	global.__objectNames[234] = "objGlobalControl";
	global.__objectNames[235] = "objEnemyMiniFire";
	global.__objectNames[236] = "objEnemyFollowBullet";
	global.__objectNames[237] = "objFreezeEnemy";
	global.__objectNames[238] = "objEnemyRocket";
	global.__objectNames[239] = "objEnemyBulletStatic";
	global.__objectNames[240] = "objEnemyBullet";
	global.__objectNames[241] = "objCutscene";
	global.__objectNames[242] = "objEnemyFireball";
	global.__objectNames[243] = "objBoat";
	global.__objectNames[244] = "objGameControl";
	global.__objectNames[245] = "objRareBird";
	global.__objectNames[246] = "objMimic";
	global.__objectNames[247] = "objBackgroundControl";
	global.__objectNames[248] = "objEntpMedallionControl";
	global.__objectNames[249] = "objEnemyCannonball";
	global.__objectNames[250] = "objBulletParent";
	global.__objectNames[251] = "objBackgroundParent";
	global.__objectNames[252] = "objShopParent";
	global.__objectNames[253] = "objWindowControl";
	global.__objectNames[254] = "objParentMedium";
	global.__objectNames[255] = "objAshFromExpl";
	global.__objectNames[256] = "objGibParent";
	global.__objectNames[257] = "objParentWeak";
	global.__objectNames[258] = "objShadowControl";
	global.__objectNames[259] = "objEnemyParent";
	global.__objectNames[260] = "objBuyParent";
	global.__objectNames[261] = "objEnemyBulletParent";
	global.__objectNames[262] = "objPauseParent";
	global.__objectNames[263] = "objMenuControl";
	global.__objectNames[264] = "objPauseControl";
	global.__objectNames[265] = "objBossParent";
	global.__objectNames[266] = "objBlood";
	global.__objectNames[267] = "objBackgroundBird";
	global.__objectNames[268] = "objBloodExplosion";
	global.__objectNames[269] = "objFadeAway";
	global.__objectNames[270] = "objRoadDecal";
	global.__objectNames[271] = "objExplosion";
	global.__objectNames[272] = "objLightning";
	global.__objectNames[273] = "objFartherClouds";
	global.__objectNames[274] = "objClouds";
	global.__objectNames[275] = "objBridge";
	global.__objectNames[276] = "objSkyline";
	global.__objectNames[277] = "objRocks";
	global.__objectNames[278] = "objFade";
	global.__objectNames[279] = "objFartherBackground";
	global.__objectNames[280] = "objBackground";
	global.__objectNames[281] = "objFarBackground";
	global.__objectNames[282] = "objStormGrey";
	global.__objectNames[283] = "objRainDrop";
	global.__objectNames[284] = "objIndicatorParticle";
	global.__objectNames[285] = "objSmoke";
	global.__objectNames[286] = "objGiblet";
	global.__objectNames[287] = "objFlash";
	global.__objectNames[288] = "objFireDebris";
	global.__objectNames[289] = "objTeleportLine";
	global.__objectNames[290] = "objTeleport";
	global.__objectNames[291] = "objGameBeginFade";
	global.__objectNames[292] = "objJunkPile";
	global.__objectNames[293] = "objForestFartherBackground";
	global.__objectNames[294] = "objJunkWall";
	global.__objectNames[295] = "objForestBackground";
	global.__objectNames[296] = "objForestFarthestBackground";
	global.__objectNames[297] = "objRoad";
	global.__objectNames[298] = "objPlayer2";
	global.__objectNames[299] = "objFriendlyJunker";
	global.__objectNames[300] = "objThickSmoke";
	global.__objectNames[301] = "objAirstrike";
	global.__objectNames[302] = "objSmokeCanister";
	global.__objectNames[303] = "objShadowManip";
	global.__objectNames[304] = "objRocketGuide";
	global.__objectNames[305] = "objBulletShell";
	global.__objectNames[306] = "objGunFlash";
	global.__objectNames[307] = "objSweat";
	global.__objectNames[308] = "objHelicopter";
	global.__objectNames[309] = "objSoulStat";
	global.__objectNames[310] = "objPickup";
	global.__objectNames[311] = "objArrow";
	global.__objectNames[312] = "objFriendlyJunkerCorpse";
	global.__objectNames[313] = "objPlayer";
	global.__objectNames[314] = "objSquareFollower";
	global.__objectNames[315] = "objMomentumBullet";
	global.__objectNames[316] = "objFlappyBullet";
	global.__objectNames[317] = "objPredictorBullet";
	global.__objectNames[318] = "objBoomerang";
	global.__objectNames[319] = "objFireball";
	global.__objectNames[320] = "objCircleBullet";
	global.__objectNames[321] = "objDove";
	global.__objectNames[322] = "objBulletDestroy";
	global.__objectNames[323] = "objInfectionShot";
	global.__objectNames[324] = "objDoveCorpse";
	global.__objectNames[325] = "objGrenade";
	global.__objectNames[326] = "objBurstBullet";
	global.__objectNames[327] = "objBullet";
	global.__objectNames[328] = "objCannonball";
	global.__objectNames[329] = "objCircle";
	global.__objectNames[330] = "objLaser";
	global.__objectNames[331] = "objApple";
	global.__objectNames[332] = "objBee";
	global.__objectNames[333] = "objBrickBreaker";
	global.__objectNames[334] = "objBestFriend";
	global.__objectNames[335] = "objBulletPortal";
	global.__objectNames[336] = "objPoisonCloud";
	global.__objectNames[337] = "objMeleeSwing";
	global.__objectNames[338] = "objBabyTurret";
	global.__objectNames[339] = "objScreamer";
	global.__objectNames[340] = "objSlingshot";
	global.__objectNames[341] = "objBoneBoyCircle";
	global.__objectNames[342] = "objScreamerWave";
	global.__objectNames[343] = "objBalloon";
	global.__objectNames[344] = "objLilPupper";
	global.__objectNames[345] = "objViolentExplosion";
	global.__objectNames[346] = "objRocket";
	global.__objectNames[347] = "objHeartBullet";
	global.__objectNames[348] = "objFlippy";
	global.__objectNames[349] = "objFriendlyDevil";
	global.__objectNames[350] = "objCigarSmoke";
	global.__objectNames[351] = "objFlippyBullet";
	global.__objectNames[352] = "objHandBullet";
	global.__objectNames[353] = "objVenomsKiss";
	global.__objectNames[354] = "objInstantLine";
	global.__objectNames[355] = "objGuardianAngel";
	global.__objectNames[356] = "objMiniFireball";
	global.__objectNames[357] = "objDespairShield";
	global.__objectNames[358] = "objGunpowderBlood";
	global.__objectNames[359] = "objHeliTurret";
	global.__objectNames[360] = "objHelpingHand";
	global.__objectNames[361] = "objLilPuffer";
	global.__objectNames[362] = "objGum";
	global.__objectNames[363] = "objSlider";
	global.__objectNames[364] = "objStatArrow";
	global.__objectNames[365] = "objSnowball";
	global.__objectNames[366] = "objStatsButton";
	global.__objectNames[367] = "objSnakeBullet";
	global.__objectNames[368] = "objArtifactsPullDown";
	global.__objectNames[369] = "objSuperBomb";
	global.__objectNames[370] = "objArtifactSelectArrow";
	global.__objectNames[371] = "objArtifactMedal";
	global.__objectNames[372] = "objMiniFire";
	global.__objectNames[373] = "objArtifactBar";
	global.__objectNames[374] = "objPlayerSelectArrow";
	global.__objectNames[375] = "objSliderGrab";
	global.__objectNames[376] = "objSnowIdol";
	global.__objectNames[377] = "objSniperSupport";
	global.__objectNames[378] = "objPickupEater";
	global.__objectNames[379] = "objCharactersPullDown";
	global.__objectNames[380] = "objBackToMenu";
	global.__objectNames[381] = "objEnemiesTab";
	global.__objectNames[382] = "objTitleD";
	global.__objectNames[383] = "objCoopArrow";
	global.__objectNames[384] = "objEntpMedallionButton";
	global.__objectNames[385] = "objCreatedBy";
	global.__objectNames[386] = "objGoButton";
	global.__objectNames[387] = "objQuitButton";
	global.__objectNames[388] = "objChallengesButton";
	global.__objectNames[389] = "objEntpMedallionArrow";
	global.__objectNames[390] = "objChallengeText";
	global.__objectNames[391] = "objChangelog";
	global.__objectNames[392] = "objLevelName";
	global.__objectNames[393] = "objCharacterBar";
	global.__objectNames[394] = "objEnemyTypeBox";
	global.__objectNames[395] = "objPauseItem";
	global.__objectNames[396] = "objItemsTab";
	global.__objectNames[397] = "objPauseMenuRestart";
	global.__objectNames[398] = "objPauseMenuMousePoint";
	global.__objectNames[399] = "objGoCoopButton";
	global.__objectNames[400] = "objPauseMenuQuit";
	global.__objectNames[401] = "objPauseMenuResume";
	global.__objectNames[402] = "objStatsTab";
	global.__objectNames[403] = "objMenuHalfFade";
	global.__objectNames[404] = "objPlayButton";
	global.__objectNames[405] = "objPausedText";
	global.__objectNames[406] = "objStatsHud";
	global.__objectNames[407] = "objPauseMenuOptions";
	global.__objectNames[408] = "objCheckBox";
	global.__objectNames[409] = "objPauseLetter";
	global.__objectNames[410] = "objItemTypeBox";
	global.__objectNames[411] = "objGamblingMachine";
	global.__objectNames[412] = "objWeaponTree";
	global.__objectNames[413] = "objPlayerSelect";
	global.__objectNames[414] = "objRestart";
	global.__objectNames[415] = "objExitButton";
	global.__objectNames[416] = "objHealth";
	global.__objectNames[417] = "objStatBox";
	global.__objectNames[418] = "objGamblingLights";
	global.__objectNames[419] = "objBossMaster";
	global.__objectNames[420] = "objGun";
	global.__objectNames[421] = "objGamblingWin";
	global.__objectNames[422] = "objGamblingDispense";
	global.__objectNames[423] = "objTitleOtherLetters";
	global.__objectNames[424] = "objTicketOfAdmission";
	global.__objectNames[425] = "objGamblingRoll";
	global.__objectNames[426] = "objBuyButton";
	global.__objectNames[427] = "objHealthRobot";
	global.__objectNames[428] = "objItem";
	global.__objectNames[429] = "objScroll";
	global.__objectNames[430] = "objUseItem";
	global.__objectNames[431] = "objShop";
	global.__objectNames[432] = "objShopkeeper";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
